name: "⚙️ Efficiency & Performance"
description: Suggest improvements for better efficiency and performance
title: "[Performance]: "
labels: ["performance"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a performance improvement!
  
  - type: textarea
    id: improvement-description
    attributes:
      label: Improvement Description
      description: A clear and concise description of the performance improvement or efficiency enhancement you suggest
      placeholder: I think performance could be improved by...
    validations:
      required: true
      
  - type: textarea
    id: current-performance
    attributes:
      label: Current Performance
      description: Describe the current performance or efficiency issue you're facing
      placeholder: Currently, when I use PackShip to...
    validations:
      required: true
      
  - type: textarea
    id: expected-improvement
    attributes:
      label: Expected Improvement
      description: Outline the expected improvement or benefit from this change
      placeholder: This change would make PackShip faster/more efficient by...
    validations:
      required: true
      
  - type: textarea
    id: metrics
    attributes:
      label: Metrics or Benchmarks
      description: If you have any metrics, benchmarks, or measurements, please share them here
      placeholder: |
        Current performance: X operations/second
        Expected performance: Y operations/second
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information, context, or suggestions that can help assess the improvement
      placeholder: More details...
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow PackShip's Code of Conduct
          required: true 