name: "📝 Documentation"
description: Report an error or area that needs clarification in documentation
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!
  
  - type: textarea
    id: issue-description
    attributes:
      label: Description of the Issue
      description: A clear and concise description of what needs to be clarified or corrected
      placeholder: The documentation is unclear about...
    validations:
      required: true
      
  - type: input
    id: issue-location
    attributes:
      label: Where is the Issue?
      description: Specify the section of the documentation where the issue occurs
      placeholder: "For example: Getting Started guide, API Reference, etc."
    validations:
      required: true
      
  - type: textarea
    id: suggested-changes
    attributes:
      label: Suggested Changes
      description: If you have any, provide your suggested changes or improvements to the documentation
      placeholder: I suggest changing/adding...
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any additional information or context that might help resolve the issue
      placeholder: More details...
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow PackShip's Code of Conduct
          required: true 